### ISSUE TITLE
panic: pprof: NewProfile name already in use: fds

### ISSUE THREAD

**Issue by chriscool** [whyrusleeping/iptb#23]
Right now I get:

```
> iptb --help
panic: pprof: NewProfile name already in use: fds

goroutine 1 [running]:
runtime/pprof.NewProfile(0x8f0720, 0x3, 0x0)
        /usr/local/go/src/runtime/pprof/pprof.go:121 +0x17d
github.com/anacrolix/missinggo/pproffd.init()
        /home/utilisateur/gocode/src/github.com/anacrolix/missinggo/pproffd/pproffd.go:10 +0x6f
github.com/anacrolix/utp.init()
        /home/utilisateur/gocode/src/github.com/anacrolix/utp/utp.go:208 +0x79
github.com/jbenet/go-multiaddr-net/utp.init()
        /home/utilisateur/gocode/src/github.com/jbenet/go-multiaddr-net/utp/utp_util.go:105 +0x45
github.com/jbenet/go-multiaddr-net.init()
        /home/utilisateur/gocode/src/github.com/jbenet/go-multiaddr-net/net.go:298 +0x5b
github.com/whyrusleeping/iptb/util.init()
        /home/utilisateur/gocode/src/github.com/whyrusleeping/iptb/util/util.go:648 +0x86
main.init()
        /home/utilisateur/gocode/src/github.com/whyrusleeping/iptb/main.go:293 +0x78

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [select]:
gx/ipfs/QmaDNZ4QMdBdku1YZWBysufYyoQt1negQGNav6PLYarbY8/go-log.(*MirrorWriter).logRoutine(0xc820012a00)
        /home/utilisateur/gocode/src/gx/ipfs/QmaDNZ4QMdBdku1YZWBysufYyoQt1negQGNav6PLYarbY8/go-log/writer.go:71 +0x33c
created by gx/ipfs/QmaDNZ4QMdBdku1YZWBysufYyoQt1negQGNav6PLYarbY8/go-log.NewMirrorWriter
        /home/utilisateur/gocode/src/gx/ipfs/QmaDNZ4QMdBdku1YZWBysufYyoQt1negQGNav6PLYarbY8/go-log/writer.go:38 +0xe2

goroutine 7 [select]:
gx/ipfs/Qmazh5oNUVsDZTs2g59rq8aYQqwpss8tcUWQzor5sCCEuH/go-log.(*MirrorWriter).logRoutine(0xc820012c40)
        /home/utilisateur/gocode/src/gx/ipfs/Qmazh5oNUVsDZTs2g59rq8aYQqwpss8tcUWQzor5sCCEuH/go-log/writer.go:71 +0x33c
created by gx/ipfs/Qmazh5oNUVsDZTs2g59rq8aYQqwpss8tcUWQzor5sCCEuH/go-log.NewMirrorWriter
        /home/utilisateur/gocode/src/gx/ipfs/Qmazh5oNUVsDZTs2g59rq8aYQqwpss8tcUWQzor5sCCEuH/go-log/writer.go:38 +0xe2
```

**Comment by chriscool** [comment]
This error goes away when I rebuild on top of PR #22 that has been merged, so maybe it's not worth investigating.

**Comment by whyrusleeping** [comment]
I think this has been resolved now
